### Numpy : Numerical Python
- 데이터과학을 위한 많은 라이브러리 중에서 가장 기본이 되는 라이브러리
- 데이터분석을 위한 패키지 판다스, 머신러닝을 이한 사이킷런, 딥러닝을 위한 텐서플로 들이 넘파이 위에서 작동한다.
    
- 데이터과학을 위한 자료값들이 그 용량이 크기 때문에 빠른 처리가 어려움 -> 넘파이는 빠르고 편하게 수치 데이터 처리가능

- o차원 -> 스칼라
- 1차원 -> 벡터 (vector) : 숫자들로 이루어진 배열
- 2차원 -> 행렬 (matrix)
- 3차원 이상, n차원 -> 다차원,텐서 n-order tensor

In [ ]:
import numpy as np

In [ ]:
# np.array 함수
# np.array( 매개변수1, 매개변수2 )
# 매개변수1 -> 데이터값
# 매개변수2 -> 데이터형, 생략가능

In [ ]:
# 행렬 생성

test_array = np.array([1, 4, 5, 8], dtype=float)

print(test_array)
print(type(test_array))
print(type(test_array[0]))

In [ ]:
# 개별적인 값 : 항목 item, 원소 element, 요소

test_array = np.array([1, 4, 5, "8"], float)
print(type(test_array[0]))

test_array = np.array([1, 4.0, 5, 8])
print(type(test_array[0]))

test_array = np.array([1, 4.0, 5, "8"])
print(type(test_array[0]))


In [ ]:
test_array = np.array([1, 4, 5, "8"], float)

print(test_array)
print(test_array.dtype) # 배열 전체의 데이터 타입 반환
print(test_array.shape) # 배열의 구조(shape)를 반환

In [ ]:
# 행렬(M*N) : 모든 값이 채워져 있어야 한다. p84

x = np.array( [1,2,3],[4,5] )
print(x)

In [ ]:
# 리스트는 2차원이 다 채워지지 않아도 된다
x=[ [1,2,3],[4,5] ]
print(x)

### 배열 구조
- 1차원, 2차원, 3차원

In [ ]:
# 배열의 구조 : 1차원, 2차원, 3차원

np1 = np.array( [1,1,1] )
print(np1)
print(np1.shape)
print('-'*20)

np1 = np.array( [ [1,1,1],[2,2,2] ] )
print(np1)
print(np1.shape)
print('-'*20)

np1 = np.array( [ [[1,1,1], [2,2,2]],
                  [[1,1,1], [2,2,2]],
                  [[1,1,1], [2,2,2]],
                  [[1,1,1], [2,2,2]], ] )
print(np1)
print(np1.shape)
print('-'*20)

print(np1.ndim)
print(np1.size)      # 전체 사이즈
print(np1.itemsize)  # 요소 사이즈

### 배열 구조 다루기

In [ ]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])

x.shape

In [ ]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])

x.reshape(-1,)

In [ ]:
# 전체 요소의 갯수가 맞지 않으면 에러
x = np.array(range(8))
print(x)

#x = reshape(2,2)
print(x)

x = x.reshape(4,2)
print(x)

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [ ]:
# 배열 구조 바꾸기
# -1 : 전체 요소의 갯수는 고정시키고, 차원이 자동으로 지정됨

x = np.array( range(8)).reshape(4,2)
print(x)
print('-'*20)

x = np.array( range(8)).reshape(-1)
print(x)
print('-'*20)

x = np.array( range(8)).reshape(4,-1)
print(x)
print('-'*20)

x = np.array( range(8)).reshape(2,2,-1)
print(x)
print('-'*20)

x = np.array( range(8)).reshape(-1, 2)
print(x)
print('-'*20)

x = np.array( range(8)).reshape(-1,2,2)
print(x)
print('-'*20)

x = np.array( range(8)).flatten()
print(x)
print('-'*20)

In [ ]:
# 배열 정렬 :  (기본이 행 안에서만 정렬 )

import random

# 2차원(3,3) 랜덤값(0~100) 생성
a = np.array( [ [ random.randint(0.100) for _ in range(3) ] for _ in range(3)])
print(a)
print('='*20)

 # 행렬 정렬 : 행 안에서 정렬
b = np.sort(a)
print ( b )
print('-'*20)

 # 행렬 정렬 : 열 안에서 정렬
b = np.sort(a, axis=0)
print ( b )
print('-'*20)


In [ ]:
# 배열 정렬 : 전체 정렬
# 평탄화-> 정렬-> 구조 재배치

# 2차원(3,3) 랜덤값(0~100) 생성 :
a=np.array( [ [ random.randint(0,100) for _ in range(3) ] for _ in range(3)])
print(a)
print('='*20)

b= a.flatten()  # 평탄화
print(b)
print('-'*20)

b = np.sort(b)  # 정렬
print(b)
print('-'*20)

a = b.reshape(3,3)  # 구조 재배치
print(a)


### **인덱싱과 슬라이싱**
- 리스트의 인덱싱과 슬라이싱 비슷
- 리스트 : x[][]
- 넘파이 : x[][], x[,] ',' 지원

In [ ]:
# 리스트 인덱싱 -> 인덱싱

x = [ [1,2,3] , [4,5,6]]
print(x)
print('-'*30)

# 1행 1열의 값을 55 로 변경

x[1][1] = 55
print(x)


In [ ]:
# 넘파이  -> 인덱싱

x = np.array( [ [1,2,3] , [4,5,6]] )
print(x)

# 1행 1열의 값을 55 로 변경

x[1,1] = 55
print(x)


In [ ]:
# 슬라이싱 :  전체 자료중에 일부만 추출

a = [ [i*j for i in range(4)] for j in range(4) ]  # 2차원 리스트
print(a)

# 위 리스트를 행렬로 변환
x = np.array(a)
print(x)

In [ ]:
# 슬라이싱 실습 #1
# x[ 행 , 열 ] , x[ 0:2 ,  0, 3] , 열 생략가능
# 행 ,열 -> 시작인덱스 : 끝인덱스+1

print(x)
print('='*20)

# 위부분 2개 행만
print( x[  0:2 , : ] )
print('-'* 20)

# 열인덱스 1과 2 만
print( x[ : , 1:3 ])
print('-'* 20)

print( x[1:3  ])
print('-'* 20)

print( x[ :2 , : ])
print('-'* 20)

In [ ]:
# 슬라이싱 실습 #2
# [시작인덱스:마지막인덱스+1:증가값]

x = np.array( range(15)).reshape(3,-1)
print(x)
print('='*20)

print( x[:, ::2])
print('-'*20)

print( x[::2, ::3])
print('-'*20)

In [ ]:
# 슬라이싱 실습 #3

x = np.array( range(15)).reshape(3,-1)
print(x)
print('='*20)

print( x[ ::-1 ])  # 행을 거꾸로 출력
print('-'*20)

print( x[ : , ::-1 ]) # 열을 거꾸로 출력
print('-'*20)

print( x[ ::-1 , ::-1 ]) # 행열을 거꾸로 출력
print('-'*20)

print( np.transpose(x))  # 행열 바꾸기
print('-'*20)

print(  x.T  )           # 행열 바꾸기 / transpose() 함수와 결과 동일
print('-'*20)


### 넘파이에서 배열 생성 함수
- arange : 차례대로 값을 생성
- ones, zeros, empty : 생성시점에서 특정값으로 생성
- ones_like, zeros_like, empty_like : 기존 넘파이구조에서 값만 셋팅
- identity, eye, diag
- 통계분석함수


In [ ]:
# arange

print( np.arange(10))
print( np.arange(-5, 5))
print( np.arange(0, 5, 0.5))


In [ ]:
# ones, zeros, empty : 생성시점에서 특정값으로 생성

print( np.ones(shape=(3,2), dtype=np.int8) )
print('-'*20)

print( np.zeros(shape=(3,2)) )
print('-'*20)

print( np.empty(shape=(3,2)) )  # 어떤값이 나올지 모른다, 공간만 생성
print('-'*20)

print( np.empty(shape=(3,2), dtype=np.float32 ))
print('-'*20)

In [ ]:
# identity : 단위행렬
# 기본 데이터 타입은 실수

x = np.identity(4, int)  # np.identity(n=4, dtype=int)
print(x)
print('-'*20)

# eye : 단위행렬, 행열의 크기 지정가능
# 행,열, 시작인덱스 기본 0
print( np.eye(3,5) )
print('-'*20)

print( np.eye(3,5,3) )
print('-'*20)

print( np.eye(N=3, M=5, k=3) )
print('-'*20)

In [ ]:
# diag :
# 대각선값 추출

x = np.arange(25).reshape(5,5)
print(x)
print('-'*20)

print( np.diag(x) )  # 대각선값 추출
print('-'*20)

print( np.diag(x, 2) )
print('-'*20)

### 넘파이 배열 연산
- 일반 통계 함수 : sum, mean, max, min, std...
- 연결 함수 : vstack, hstack, concatenate
- 브로드케스팅

In [ ]:
# 통계 분석 함수

# 난수(0~10 사이)를 발생시켜, 3*3 넘파이 생성
a = np.random.randint( 0, 10, size=(3,3) )

print(a)
print('='*20)

print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print('-'*20)

# 전체 합계의 다른 표현식
print( a.sum() )

# 열별 집계
print( a.sum(axis=0) )

# 행별 집계
print( a.sum(axis=1) )

In [ ]:
# 중복값 제거 :  교재에는 없음
a = np.array( [1,2,2,2,2,3,3,3,3,4,5] )
print(a)

print( np.unique(a))

# 공통된 값 : 교재에는 없음
a = np.array( [1,2,3,4,5,6] )
b = np.array( [4,5,6] )

print(np.intersect1d(a,b))

In [ ]:
# 연결 함수 실습을 위한  원본 데이터

a=np.arange(9).reshape(3, 3)
b=a*2

print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [ ]:
# 연결 함수_#1
# vstack : vertical stack : 세로 : 위아래로 연결
# hstack : horizontal stack : 가로 : 좌우로 연렬

# 위아래 : vstack()
v=np.vstack((a, b))
print(v, v.shape)

print('-----------------------')

# 옆으로 : hstack 함수
h=np.hstack((a, b))
print(h, h.shape)


In [ ]:
# 연결 함수_#2  : concatenate 함수 ,

# 위아래 연결
x=np.concatenate((a, b), axis=0)

print(x)
print(x.shape)
print()

# 옆으로 연결
y=np.concatenate((a, b), axis=1)

print(y)
print(y.shape)

### 사칙 연산 함수

In [ ]:
# 사칙 연산 함수
# 행렬간, 벡터간 +, - 연산 가능
# 구조가 같으면 기본적으로 요소간 연산이 발생

x = np.arange(1,7).reshape(2,3)
print(x)
print('='*20)

print( x + x )
print('='*20)



In [ ]:
# 브로드캐스팅 #1
# 행렬과 스칼라값 연산 : p 110

x = np.arange(1, 10).reshape(3,3)
print(x)
print('='*20)

print(x + 10)
print('-'*20)

print(x - 3)
print('-'*20)

print(x * 3)
print('-'*20)

In [4]:
import numpy as np

# 브로드캐스팅 #2
# 행렬과 벡터 간 연산 : p 111

a = np.arange(1, 13).reshape(4,3)  # 행렬
print(a)
print('-'*20)
b = np.arange(10,40,10)   # 벡터
print(b)
print('='*20)

print(a + b)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------
[10 20 30]
[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


In [ ]:
import numpy as np

# 브로드캐스팅 #3
# 행렬과 벡터 간 연산이 안되는 경우
# 위 코드 복사하여 실습

a = np.arange(1, 13).reshape(4,3)  # 행렬
print(a)
print('-'*20)
b = np.array( [10,20] )   # 벡터
print(b)
print('='*20)

print(a + b)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------
[10 20]


ValueError: operands could not be broadcast together with shapes (4,3) (2,) 

### 비교 연산과 데이터 추출
- 비교연산 : 벡터-스칼라, 벡터-벡터

In [16]:
# 벡터-스칼라 비교연산 ==> 결과는 불린형 (True, False)

a = np.random.randint(0,100, size=5)
print(a)
print('-------------------------------------------')

print( a > 50 )


[42 50 74 72 88]
-------------------------------------------
[False False  True  True  True]


In [18]:
# 벡터-벡터 비교연산 ==> 결과는 불린형 (True, False)

a = np.random.randint(0,100, size=5)
b = np.random.randint(0,100, size=5)
c = np.random.randint(0,100, size=3)

print(a)
print(b)
print('-------------------------------------------')

print( a > b )
print('-------------------------------------------')

# 벡터의 사이즈가 다르면 안됨!

#print( a > c ) ValueError: operands could not be broadcast together with shapes (5,) (3,) 

[77 11 70 26 84]
[74 93 97 25 41]
-------------------------------------------
[ True False False  True  True]
-------------------------------------------


In [19]:
# all, any

x = np.random.randint(0,10, size=5)
print(x)
print('-------------------------------------------')

print( x > 3 )
print( (x > 3).all()  )  # 행렬 안의 값이 모두 비교연산을 만족
print('-------------------------------------------')

print( (x > 3).any()  )  # 행렬 안의 값중 아무거나 비교연산을 만족
print('-------------------------------------------')

[5 5 2 7 2]
-------------------------------------------
[ True  True False  True False]
False
-------------------------------------------
True
-------------------------------------------


In [20]:
# 인덱스 반환 함수 : where함수
# 행렬에서 조건에 맞는 값들의 위치(인덱스) 반환

x = np.random.randint(0,100, size=10)
print(x)
print('-------------------------------------------')

# 50 이상 값의 위치
print(  np.where(x >= 50)  )
print('-------------------------------------------')

# 조건 여러개 &, |  // 50~70 값의 위치
print(  np.where((x >= 50) & (x <= 70))  )
print('-------------------------------------------')

# 50보다 크다 // 참이면 10, 아니면 20
print(  np.where(x > 50, 10, 20)  )
print('-------------------------------------------')


[26 26 11 70 53  2 62 10 58  4]
-------------------------------------------
(array([3, 4, 6, 8]),)
-------------------------------------------
(array([3, 4, 6, 8]),)
-------------------------------------------
[20 20 20 10 10 20 10 20 10 20]
-------------------------------------------


In [21]:
# 행렬에서 조건에 맞는 값들을 반환 : 위치가 아닌 값!!!

x = np.random.randint(0,100, size=10)
print(x)
print('-------------------------------------------')

# 50 이상의 값
print(  x[ x >= 50 ]  )
a = x[ x >= 50 ]
print('-------------------------------------------')

# 50~80 사이의 값
print(  x[ (x >= 50) & (x <= 80) ]  )
print('-------------------------------------------')

# 짝수만
print( x[ x % 2 == 0 ]  )
print('-------------------------------------------')

# 평균값 보다 작은 값
print( x[ x < x.mean() ] )
print('-------------------------------------------')

# 50보다 큰값들의 합계
print( x[ x > 50 ].sum() )

[55 45 98 22  6 80 67  6 48 22]
-------------------------------------------
[55 98 80 67]
-------------------------------------------
[55 80 67]
-------------------------------------------
[98 22  6 80  6 48 22]
-------------------------------------------
[22  6  6 22]
-------------------------------------------
300
