In [ ]:
### 1번
import numpy as np

test_a = np.array([[4, 8], [2, 9]])
print(test_a * test_a)

# 정답 1번

[[16 64]
 [ 4 81]]


In [ ]:
### 2번
import numpy as np

test_a = np.array([[5, 5, 5],[3, 3, 3]])
print(test_a ** 2)

#정답 2번

[[25 25 25]
 [ 9  9  9]]


In [ ]:
### 3번
import numpy as np

a = np.array([[3, 22, 2], [3, 1, 5]])
b = np.array([[6, 7, 9], [2, 1, 3]])

print(a * b)
print(a.T.dot(b))
print(a.dot(b))
print(a.dot(b.T))

# 정답 2번

[[ 18 154  18]
 [  6   1  15]]
[[ 24  24  36]
 [134 155 201]
 [ 22  19  33]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
### 7번
import numpy as np

test_a = np.arange(1,10).reshape(3,3)
test_b = np.arange(6).reshape(2,3)

test_a.dot(test_b.T)

# 정답 4번

array([[ 8, 26],
       [17, 62],
       [26, 98]])

In [ ]:
### 8번

#정답 1, 3

In [ ]:
### 9번
import numpy as np

arr = np.arange(16).reshape(4, 4)
print(arr.size - arr.shape[0] * arr.ndim)

# 정답 3번

8


In [ ]:
### 10번
import numpy as np

arr = np.arange(20).reshape(10, 2)
x, y = arr.shape

print(arr.reshape(y, x).shape)

# 정답 2번


(2, 10)


In [ ]:
### 11번
import numpy as np

arr = np.arange(24)
arr =arr.reshape(4, 6)

# 정답 1번

In [ ]:
### 12번
import numpy as np

arr = np.arange(8)

print(arr.flatten())
print(arr.reshape(2, -2))
print(arr.reshape(arr.size))
print(arr)

# 정답 2번

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


In [ ]:
### 13번
import numpy as np

arr_1 =np.arange(4)
arr_2 =np.arange(4, 0, -1)

np.any(arr_1 < arr_2)

# 정답 2번

np.True_

In [ ]:
### 14번

import numpy as np

a = np.arange(6).reshape(2, 3)
b = a > 4
a[b]

# 정답 1번

array([5])

In [ ]:
### 15번

import numpy as np

X = np.array([1, 2, 3, 4, 5, 6, 7])
target_value = 4.3

def find_nearest_value(X, target_value):
       result = X[np.argmin(np.abs(X - target_value))]
       return result

find_nearest_value(X, target_value)

# 정답 3번

np.int64(4)

In [ ]:
### 16번

Z = np.array([6, 6, 6, 4, 7, 9, 1, 8, 8, 4])
Z[Z.argsort()[:5]] = 0
print(Z)

# 정답 4번

[6 0 0 0 7 9 0 8 8 0]


In [ ]:
### 17번

arr = np.array([[17, 27, 14, 11],
                [8, 24, 25, 26],
                [11, 26, 26, 23],
                [22, 18, 24, 11]])
print(arr[[0, 2, 1]])

# 정답 1번

[[17 27 14 11]
 [11 26 26 23]
 [ 8 24 25 26]]
